### ISSUE TITLE
Podspec not being in root breaks pod install

### ISSUE THREAD

**Issue by davidpaulhunt** [VerizonAdPlatforms/VerizonVideoPartnerSDK-PlayerCore-iOS#65]
Trying to `pod install` the `PlayerCore` for use with the Partner SDK is broken because the podspec is not in the root directory.

Here's a link to the cocoapods page: https://guides.cocoapods.org/syntax/podfile.html#pod

It states
> The podspec file is expected to be in the root of the repository, if this library does not have a podspec file in its repository yet, you will have to use one of the approaches outlined in the sections below.

I'm trying to install it like this: `pod 'PlayerCore', :podspec => 'https://github.com/VerizonAdPlatforms/VerizonVideoPartnerSDK-PlayerCore-iOS`

**Comment by RomanTysiachnik** [comment]
Hi @davidpaulhunt. 

You can simply add VVP SDK poid in your Podfile and it will fetch all its dependencies, including Player Core.

You should check this file to see how it works.
https://github.com/VerizonAdPlatforms/VerizonVideoPartnerSDK-iOS/blob/master/VerizonVideoPartnerSDK.podspec

**Comment by RomanTysiachnik** [comment]
The reason for that is because of PlayerCore contains only business logic for that specific SDK (like working with VRM, VPAID etc.)

**Comment by davidpaulhunt** [comment]
@RomanTysiachnik thanks for the response.

I understand and was able to install all the appropriate pods by adding a proper source to my pod file. I referenced it here https://github.com/VerizonAdPlatforms/VerizonVideoPartnerSDK-iOS/issues/125#issuecomment-552508111

Feel free to close this issue.
